// struct "GameClasses", field name "StartingStats", pointer name: "StartingStats"
// struct "GameClasses", field name "HPFactor", size field/pointer name: "HPFactor_size"
// struct "GameClasses", field name "SPBase", size field/pointer name: "SPBase_size"
// struct "GameClasses", field name "startingStats", size field/pointer name: "startingStats_size"
// struct "GameClasses", field name "SPFactor", size field/pointer name: "SPFactor_size"
// struct "GameClasses", field name "SPFactor", pointer name: "SPFactor"
// struct "GameClasses", field name "skills", size field/pointer name: "skills_size"
// struct "GameClasses", field name "Skills", pointer name: "Skills"
// struct "GameClasses", field name "SPBase", pointer name: "SPBase"
// struct "GameClasses", field name "HPBase", size field/pointer name: "HPBase_size"
// struct "GameClasses", field name "HPBase", pointer name: "HPBase"
// struct "GameClasses", field name "SPStats", pointer name: "SPStats"
// struct "GameClasses", field name "SPStats", size field/pointer name: "SPStats_size"
// struct "GameClasses", field name "HPFactor", pointer name: "HPFactor"
// struct "GameClassKinds", field name "StartingSkills", pointer name: "StartingSkills"
// struct "GameClassKinds", field name "startingSkills", size field/pointer name: "startingSkills_size"
// struct "SpritesLod", field name "spritesSW", size field/pointer name: "spritesSW_size"
// struct "SpritesLod", field name "SpritesSW", pointer name: "SpritesSW"
// struct "GameStructure", field name "NPCDataTxt", pointer name: "NPCDataTxt"
// struct "GameStructure", field name "transportLocations", size field/pointer name: "transportLocations_size"
// struct "GameStructure", field name "titleTrackOffset", size field/pointer name: "titleTrackOffset_size"
// struct "GameStructure", field name "hostileTxt", size field/pointer name: "hostileTxt_size"
// struct "GameStructure", field name "NPCGroup", pointer name: "NPCGroup"
// struct "GameStructure", field name "monstersTxt", size field/pointer name: "monstersTxt_size"
// struct "GameStructure", field name "TransTxt", pointer name: "TransTxt"
// struct "GameStructure", field name "MonsterKinds", pointer name: "MonsterKinds"
// struct "GameStructure", field name "shopSpecialItems", size field/pointer name: "shopSpecialItems_size"
// struct "GameStructure", field name "ShopTheftExpireTime", pointer name: "ShopTheftExpireTime"
// struct "GameStructure", field name "transTxt", size field/pointer name: "transTxt_size"
// struct "GameStructure", field name "guildItems", size field/pointer name: "guildItems_size"
// struct "GameStructure", field name "shopItems", size field/pointer name: "shopItems_size"
// struct "GameStructure", field name "questsTxt", size field/pointer name: "questsTxt_size"
// struct "GameStructure", field name "GlobalEvtLines", pointer name: "GlobalEvtLines"
// struct "GameStructure", field name "TransportIndex", pointer name: "TransportIndex"
// struct "GameStructure", field name "Houses", pointer name: "Houses"
// struct "GameStructure", field name "AwardsSort", pointer name: "AwardsSort"
// struct "GameStructure", field name "NPCGroup", size field/pointer name: "NPCGroup_size"
// struct "GameStructure", field name "NPCNews", pointer name: "NPCNews"
// struct "GameStructure", field name "autonoteCategory", size field/pointer name: "autonoteCategory_size"
// struct "GameStructure", field name "globalEvtLines", size field/pointer name: "globalEvtLines_size"
// struct "GameStructure", field name "ShopItems", pointer name: "ShopItems"
// struct "GameStructure", field name "QuestsTxt", pointer name: "QuestsTxt"
// struct "GameStructure", field name "ShopSpecialItems", pointer name: "ShopSpecialItems"
// struct "GameStructure", field name "AutonoteCategory", pointer name: "AutonoteCategory"
// struct "GameStructure", field name "TitleTrackOffset", pointer name: "TitleTrackOffset"
// struct "GameStructure", field name "ClassNames", pointer name: "ClassNames"
// struct "GameStructure", field name "HousesExtra", pointer name: "HousesExtra"
// struct "GameStructure", field name "HouseMovies", pointer name: "HouseMovies"
// struct "GameStructure", field name "GuildNextRefill2", pointer name: "GuildNextRefill2"
// struct "GameStructure", field name "ShopNextRefill", pointer name: "ShopNextRefill"
// struct "GameStructure", field name "monsterKinds", size field/pointer name: "monsterKinds_size"
// struct "GameStructure", field name "CharacterPortraits", pointer name: "CharacterPortraits"
// struct "GameStructure", field name "transportIndex", size field/pointer name: "transportIndex_size"
// struct "GameStructure", field name "mapDoorSound", size field/pointer name: "mapDoorSound_size"
// struct "GameStructure", field name "NPCDataTxt", size field/pointer name: "NPCDataTxt_size"
// struct "GameStructure", field name "TransportLocations", pointer name: "TransportLocations"
// struct "GameStructure", field name "NPCText", pointer name: "NPCText"
// struct "GameStructure", field name "MonstersTxt", pointer name: "MonstersTxt"
// struct "GameStructure", field name "placeMonTxt", size field/pointer name: "placeMonTxt_size"
// struct "GameStructure", field name "PatchOptions", pointer name: "PatchOptions"
// struct "GameStructure", field name "itemsTxt", size field/pointer name: "itemsTxt_size"
// struct "GameStructure", field name "shopTheftExpireTime", size field/pointer name: "shopTheftExpireTime_size"
// struct "GameStructure", field name "ItemsTxt", pointer name: "ItemsTxt"
// struct "GameStructure", field name "autonoteTxt", size field/pointer name: "autonoteTxt_size"
// struct "GameStructure", field name "NPCTopic", size field/pointer name: "NPCTopic_size"
// struct "GameStructure", field name "NPC", pointer name: "NPC"
// struct "GameStructure", field name "MapDoorSound", pointer name: "MapDoorSound"
// struct "GameStructure", field name "mixPotions", size field/pointer name: "mixPotions_size"
// struct "GameStructure", field name "houses", size field/pointer name: "houses_size"
// struct "GameStructure", field name "characterDollTypes", size field/pointer name: "characterDollTypes_size"
// struct "GameStructure", field name "characterPortraits", size field/pointer name: "characterPortraits_size"
// struct "GameStructure", field name "MixPotions", pointer name: "MixPotions"
// struct "GameStructure", field name "ReagentSettings", pointer name: "ReagentSettings"
// struct "GameStructure", field name "NPCGreet", size field/pointer name: "NPCGreet_size"
// struct "GameStructure", field name "NPCText", size field/pointer name: "NPCText_size"
// struct "GameStructure", field name "mapFogChances", size field/pointer name: "mapFogChances_size"
// struct "GameStructure", field name "MissileSetup", pointer name: "MissileSetup"
// struct "GameStructure", field name "MapFogChances", pointer name: "MapFogChances"
// struct "GameStructure", field name "mapStats", size field/pointer name: "mapStats_size"
// struct "GameStructure", field name "NPC", size field/pointer name: "NPC_size"
// struct "GameStructure", field name "missileSetup", size field/pointer name: "missileSetup_size"
// struct "GameStructure", field name "NPCTopic", pointer name: "NPCTopic"
// struct "GameStructure", field name "NPCGreet", pointer name: "NPCGreet"
// struct "GameStructure", field name "AutonoteTxt", pointer name: "AutonoteTxt"
// struct "GameStructure", field name "MapStats", pointer name: "MapStats"
// struct "GameStructure", field name "CharacterDollTypes", pointer name: "CharacterDollTypes"
// struct "GameStructure", field name "housesExtra", size field/pointer name: "housesExtra_size"
// struct "GameStructure", field name "CustomLods", pointer name: "CustomLods"
// struct "GameStructure", field name "PlaceMonTxt", pointer name: "PlaceMonTxt"
// struct "GameStructure", field name "NPCNews", size field/pointer name: "NPCNews_size"
// struct "GameStructure", field name "guildNextRefill2", size field/pointer name: "guildNextRefill2_size"
// struct "GameStructure", field name "reagentSettings", size field/pointer name: "reagentSettings_size"
// struct "GameStructure", field name "houseMovies", size field/pointer name: "houseMovies_size"
// struct "GameStructure", field name "GuildItems", pointer name: "GuildItems"
// struct "GameStructure", field name "awardsSort", size field/pointer name: "awardsSort_size"
// struct "GameStructure", field name "HostileTxt", pointer name: "HostileTxt"
// struct "GameStructure", field name "classNames", size field/pointer name: "classNames_size"
// struct "GameStructure", field name "shopNextRefill", size field/pointer name: "shopNextRefill_size"
// struct "DialogLogic", field name "List", pointer name: "List"
// struct "DialogLogic", field name "list", size field/pointer name: "list_size"