// struct "ArmorPicsCoords", field name "Belts", pointer name: "Belts"
// struct "ArmorPicsCoords", field name "cloaks", size field/pointer name: "cloaks_size"
// struct "ArmorPicsCoords", field name "Cloaks", pointer name: "Cloaks"
// struct "ArmorPicsCoords", field name "boots", size field/pointer name: "boots_size"
// struct "ArmorPicsCoords", field name "belts", size field/pointer name: "belts_size"
// struct "ArmorPicsCoords", field name "helms", size field/pointer name: "helms_size"
// struct "ArmorPicsCoords", field name "Helms", pointer name: "Helms"
// struct "ArmorPicsCoords", field name "Boots", pointer name: "Boots"
// struct "ArmorPicsCoords", field name "Armors", pointer name: "Armors"
// struct "ArmorPicsCoords", field name "armors", size field/pointer name: "armors_size"
// struct "CharacterVoices", field name "Sounds", pointer name: "Sounds"
// struct "CharacterVoices", field name "avail", size field/pointer name: "avail_size"
// struct "CharacterVoices", field name "Avail", pointer name: "Avail"
// struct "CharacterVoices", field name "sounds", size field/pointer name: "sounds_size"
// struct "GameClassKinds", field name "StartingSkills", pointer name: "StartingSkills"
// struct "GameClassKinds", field name "startingSkills", size field/pointer name: "startingSkills_size"
// struct "GameParty", field name "QBits", pointer name: "QBits"
// struct "GameParty", field name "QBits", size field/pointer name: "QBits_size"
// struct "HouseRules", field name "weaponShopsStandart", size field/pointer name: "weaponShopsStandart_size"
// struct "HouseRules", field name "arcomageTexts", size field/pointer name: "arcomageTexts_size"
// struct "HouseRules", field name "magicShopsSpecial", size field/pointer name: "magicShopsSpecial_size"
// struct "HouseRules", field name "arcomage", size field/pointer name: "arcomage_size"
// struct "HouseRules", field name "MagicShopsSpecial", pointer name: "MagicShopsSpecial"
// struct "HouseRules", field name "armorShopsStandart", size field/pointer name: "armorShopsStandart_size"
// struct "HouseRules", field name "spellbookShops", size field/pointer name: "spellbookShops_size"
// struct "HouseRules", field name "alchemistsStandart", size field/pointer name: "alchemistsStandart_size"
// struct "HouseRules", field name "Arcomage", pointer name: "Arcomage"
// struct "HouseRules", field name "AlchemistsStandart", pointer name: "AlchemistsStandart"
// struct "HouseRules", field name "WeaponShopsStandart", pointer name: "WeaponShopsStandart"
// struct "HouseRules", field name "MagicShopsStandart", pointer name: "MagicShopsStandart"
// struct "HouseRules", field name "training", size field/pointer name: "training_size"
// struct "HouseRules", field name "weaponShopsSpecial", size field/pointer name: "weaponShopsSpecial_size"
// struct "HouseRules", field name "magicShopsStandart", size field/pointer name: "magicShopsStandart_size"
// struct "HouseRules", field name "WeaponShopsSpecial", pointer name: "WeaponShopsSpecial"
// struct "HouseRules", field name "Training", pointer name: "Training"
// struct "HouseRules", field name "alchemistsSpecial", size field/pointer name: "alchemistsSpecial_size"
// struct "HouseRules", field name "ArcomageTexts", pointer name: "ArcomageTexts"
// struct "HouseRules", field name "SpellbookShops", pointer name: "SpellbookShops"
// struct "HouseRules", field name "ArmorShopsSpecial", pointer name: "ArmorShopsSpecial"
// struct "HouseRules", field name "armorShopsSpecial", size field/pointer name: "armorShopsSpecial_size"
// struct "HouseRules", field name "AlchemistsSpecial", pointer name: "AlchemistsSpecial"
// struct "HouseRules", field name "ArmorShopsStandart", pointer name: "ArmorShopsStandart"
// struct "GameClasses", field name "HPFactor", size field/pointer name: "HPFactor_size"
// struct "GameClasses", field name "startingStats", size field/pointer name: "startingStats_size"
// struct "GameClasses", field name "StartingStats", pointer name: "StartingStats"
// struct "GameClasses", field name "SPStats", pointer name: "SPStats"
// struct "GameClasses", field name "skills", size field/pointer name: "skills_size"
// struct "GameClasses", field name "Skills", pointer name: "Skills"
// struct "GameClasses", field name "SPFactor", pointer name: "SPFactor"
// struct "GameClasses", field name "SPFactor", size field/pointer name: "SPFactor_size"
// struct "GameClasses", field name "SPBase", pointer name: "SPBase"
// struct "GameClasses", field name "HPBase", size field/pointer name: "HPBase_size"
// struct "GameClasses", field name "HPBase", pointer name: "HPBase"
// struct "GameClasses", field name "SPBase", size field/pointer name: "SPBase_size"
// struct "GameClasses", field name "SPStats", size field/pointer name: "SPStats_size"
// struct "GameClasses", field name "HPFactor", pointer name: "HPFactor"
// struct "SpritesLod", field name "spritesSW", size field/pointer name: "spritesSW_sizePtr"
// struct "SpritesLod", field name "SpritesSW", pointer name: "SpritesSW"
// struct "DialogLogic", field name "List", pointer name: "List"
// struct "DialogLogic", field name "list", size field/pointer name: "list_sizePtr"
// struct "GameStructure", field name "NPCDataTxt", pointer name: "NPCDataTxt"
// struct "GameStructure", field name "transportLocations", size field/pointer name: "transportLocations_size"
// struct "GameStructure", field name "titleTrackOffset", size field/pointer name: "titleTrackOffset_size"
// struct "GameStructure", field name "hostileTxt", size field/pointer name: "hostileTxt_size"
// struct "GameStructure", field name "NPCGroup", pointer name: "NPCGroup"
// struct "GameStructure", field name "AwardsTxt", pointer name: "AwardsTxt"
// struct "GameStructure", field name "monstersTxt", size field/pointer name: "monstersTxt_sizePtr"
// struct "GameStructure", field name "TransTxt", pointer name: "TransTxt"
// struct "GameStructure", field name "NPCText", size field/pointer name: "NPCText_size"
// struct "GameStructure", field name "shopSpecialItems", size field/pointer name: "shopSpecialItems_size"
// struct "GameStructure", field name "ShopTheftExpireTime", pointer name: "ShopTheftExpireTime"
// struct "GameStructure", field name "itemsTxt", size field/pointer name: "itemsTxt_sizePtr"
// struct "GameStructure", field name "guildItems", size field/pointer name: "guildItems_size"
// struct "GameStructure", field name "shopItems", size field/pointer name: "shopItems_size"
// struct "GameStructure", field name "awardsTxt", size field/pointer name: "awardsTxt_size"
// struct "GameStructure", field name "GlobalEvtLines", pointer name: "GlobalEvtLines"
// struct "GameStructure", field name "MissileSetup", pointer name: "MissileSetup"
// struct "GameStructure", field name "mapStats", size field/pointer name: "mapStats_sizePtr"
// struct "GameStructure", field name "AwardsSort", pointer name: "AwardsSort"
// struct "GameStructure", field name "NPCGroup", size field/pointer name: "NPCGroup_size"
// struct "GameStructure", field name "NPCNews", pointer name: "NPCNews"
// struct "GameStructure", field name "autonoteCategory", size field/pointer name: "autonoteCategory_size"
// struct "GameStructure", field name "globalEvtLines", size field/pointer name: "globalEvtLines_sizePtr"
// struct "GameStructure", field name "ShopItems", pointer name: "ShopItems"
// struct "GameStructure", field name "QuestsTxt", pointer name: "QuestsTxt"
// struct "GameStructure", field name "ShopSpecialItems", pointer name: "ShopSpecialItems"
// struct "GameStructure", field name "AutonoteCategory", pointer name: "AutonoteCategory"
// struct "GameStructure", field name "TitleTrackOffset", pointer name: "TitleTrackOffset"
// struct "GameStructure", field name "PlaceMonTxt", pointer name: "PlaceMonTxt"
// struct "GameStructure", field name "HousesExtra", pointer name: "HousesExtra"
// struct "GameStructure", field name "HouseMovies", pointer name: "HouseMovies"
// struct "GameStructure", field name "GuildNextRefill2", pointer name: "GuildNextRefill2"
// struct "GameStructure", field name "SpcItemsTxt", pointer name: "SpcItemsTxt"
// struct "GameStructure", field name "MonstersTxt", pointer name: "MonstersTxt"
// struct "GameStructure", field name "monsterKinds", size field/pointer name: "monsterKinds_sizePtr"
// struct "GameStructure", field name "CharacterPortraits", pointer name: "CharacterPortraits"
// struct "GameStructure", field name "transportIndex", size field/pointer name: "transportIndex_size"
// struct "GameStructure", field name "mapDoorSound", size field/pointer name: "mapDoorSound_size"
// struct "GameStructure", field name "NPCDataTxt", size field/pointer name: "NPCDataTxt_size"
// struct "GameStructure", field name "TransportLocations", pointer name: "TransportLocations"
// struct "GameStructure", field name "InOODialog", pointer name: "InOODialog"
// struct "GameStructure", field name "NPCText", pointer name: "NPCText"
// struct "GameStructure", field name "TransportIndex", pointer name: "TransportIndex"
// struct "GameStructure", field name "transTxt", size field/pointer name: "transTxt_size"
// struct "GameStructure", field name "stdItemsTxt", size field/pointer name: "stdItemsTxt_size"
// struct "GameStructure", field name "StdItemsTxt", pointer name: "StdItemsTxt"
// struct "GameStructure", field name "spcItemsTxt", size field/pointer name: "spcItemsTxt_size"
// struct "GameStructure", field name "placeMonTxt", size field/pointer name: "placeMonTxt_sizePtr"
// struct "GameStructure", field name "ShopNextRefill", pointer name: "ShopNextRefill"
// struct "GameStructure", field name "shopNextRefill", size field/pointer name: "shopNextRefill_size"
// struct "GameStructure", field name "shopTheftExpireTime", size field/pointer name: "shopTheftExpireTime_size"
// struct "GameStructure", field name "reagentSettings", size field/pointer name: "reagentSettings_size"
// struct "GameStructure", field name "CharacterDollTypes", pointer name: "CharacterDollTypes"
// struct "GameStructure", field name "questsTxt", size field/pointer name: "questsTxt_size"
// struct "GameStructure", field name "ItemsTxt", pointer name: "ItemsTxt"
// struct "GameStructure", field name "MapDoorSound", pointer name: "MapDoorSound"
// struct "GameStructure", field name "mixPotions", size field/pointer name: "mixPotions_size"
// struct "GameStructure", field name "PatchOptions", pointer name: "PatchOptions"
// struct "GameStructure", field name "characterDollTypes", size field/pointer name: "characterDollTypes_size"
// struct "GameStructure", field name "NPC", pointer name: "NPC"
// struct "GameStructure", field name "NPCTopic", size field/pointer name: "NPCTopic_size"
// struct "GameStructure", field name "ReagentSettings", pointer name: "ReagentSettings"
// struct "GameStructure", field name "NPCGreet", size field/pointer name: "NPCGreet_size"
// struct "GameStructure", field name "NPC", size field/pointer name: "NPC_size"
// struct "GameStructure", field name "GuildItems", pointer name: "GuildItems"
// struct "GameStructure", field name "guildNextRefill2", size field/pointer name: "guildNextRefill2_size"
// struct "GameStructure", field name "MapFogChances", pointer name: "MapFogChances"
// struct "GameStructure", field name "Houses", pointer name: "Houses"
// struct "GameStructure", field name "CustomLods", pointer name: "CustomLods"
// struct "GameStructure", field name "missileSetup", size field/pointer name: "missileSetup_sizePtr"
// struct "GameStructure", field name "NPCTopic", pointer name: "NPCTopic"
// struct "GameStructure", field name "NPCGreet", pointer name: "NPCGreet"
// struct "GameStructure", field name "AutonoteTxt", pointer name: "AutonoteTxt"
// struct "GameStructure", field name "MapStats", pointer name: "MapStats"
// struct "GameStructure", field name "houses", size field/pointer name: "houses_size"
// struct "GameStructure", field name "housesExtra", size field/pointer name: "housesExtra_size"
// struct "GameStructure", field name "HostileTxt", pointer name: "HostileTxt"
// struct "GameStructure", field name "mapFogChances", size field/pointer name: "mapFogChances_size"
// struct "GameStructure", field name "NPCNews", size field/pointer name: "NPCNews_size"
// struct "GameStructure", field name "autonoteTxt", size field/pointer name: "autonoteTxt_size"
// struct "GameStructure", field name "characterPortraits", size field/pointer name: "characterPortraits_size"
// struct "GameStructure", field name "houseMovies", size field/pointer name: "houseMovies_size"
// struct "GameStructure", field name "MixPotions", pointer name: "MixPotions"
// struct "GameStructure", field name "awardsSort", size field/pointer name: "awardsSort_size"
// struct "GameStructure", field name "MonsterKinds", pointer name: "MonsterKinds"
// struct "GameStructure", field name "classNames", size field/pointer name: "classNames_size"
// struct "GameStructure", field name "ClassNames", pointer name: "ClassNames"